CREATE TABLE "users" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "login" varchar(50) UNIQUE NOT NULL,
  "email" varchar(191) NOT NULL,
  "password" varchar(255) NOT NULL,
  "created" timestamp NOT NULL DEFAULT (current_timestamp)
);

CREATE TABLE "tables" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "name" varchar(50) UNIQUE NOT NULL,
  "password" varchar(255) DEFAULT null,
  "count" integer NOT NULL DEFAULT 0,
  "created" timestamp NOT NULL DEFAULT (current_timestamp),
  "user_id" integer NOT NULL
);

CREATE TABLE "options" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "type_adding" varchar(10) NOT NULL DEFAULT 'fast',
  "round_step" integer NOT NULL DEFAULT 10,
  "hidden_cols" json NOT NULL DEFAULT '{"number":false,"entity":false,"description":false}',
  "using_keys" json NOT NULL DEFAULT '{"delete":"Delete","up":"ArrowUp","down":"ArrowDown"}',
  "table_id" integer NOT NULL
);

CREATE TABLE "entities" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "key" varchar(50) NOT NULL,
  "rate" integer NOT NULL,
  "text" varchar(50) NOT NULL,
  "option_id" integer NOT NULL,
  "table_id" integer NOT NULL
);

CREATE TABLE "table_rows" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "start" timestamp NOT NULL,
  "finish" timestamp NOT NULL,
  "is_paid" boolean DEFAULT false,
  "description" varchar(255),
  "order" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "table_id" integer NOT NULL,
  "entity_id" integer NOT NULL
);

ALTER TABLE "tables" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "options" ADD FOREIGN KEY ("table_id") REFERENCES "tables" ("id");

ALTER TABLE "entities" ADD FOREIGN KEY ("option_id") REFERENCES "options" ("id");

ALTER TABLE "table_rows" ADD FOREIGN KEY ("table_id") REFERENCES "tables" ("id");

ALTER TABLE "table_rows" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("id");

ALTER TABLE "entities" ADD FOREIGN KEY ("table_id") REFERENCES "tables" ("id");
